@startuml

class Main{
+ void main(String[])
}

class Ctes{
}

class Mapa{
 -Territorios HashMap<Territorio>
 +String toString()
}

class Territorio{
 - String nombre
 - Jugador propietario
 - int ejercitos
 - List<Territorio> vecinos
}

class Jugador{
    - String nombre
    - int ejercitosDisponibles
    - char siglas
}

class Jugada{
    -jugadores ArrayList<Jugador, int>
    -mapa Mapa
    -turnoJugador int
    +void avanzarTurno()
    +Territorio atacar()
    +Mapa mostrarMapa()
    +verVecinos(Territorio)
    +verTusTerritorios()
    +colocarEjercitos(Territorio)
}

class Gui{
    +void mostrarMenu()
    +int leerOpcion()
}

class Tirada{
    -int valor1
    -int valor2
    -int valor3
    -int numDados
    +Tirada(int nDados)
    +void ordenarDados()
    +int compararTirada(Tirada otra)
    +int getValor(int Indice)
}

class Dado{
    -int resultado
    +tirar()
}

Main ..> Gui

Mapa *--> Territorio

Gui ..> Jugada

Jugada *--> Jugador

Territorio *--> Territorio

Tirada *--> Tirada

Territorio *--> Jugador

Jugada ..> Tirada

Tirada *--> Dado

Jugada ..> Mapa


@enduml